name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: checkout
        with:
          submodules: recursive
      - name: Install dependencies
        id: dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev
      - name: Get date
        id: get-date
        # purge cache weekly to refresh updated dependencies
        run: echo "date=$(date -u "+%Y-%W")" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            ~/.cargo/.*
            target/
          key: "${{ runner.os }}-cargo-${{ steps.get-date.outputs.date }}\
            -${{ hashFiles('Cargo.toml') }}"
      - name: Test
        timeout-minutes: 5
        run: cargo test --verbose
      - name: Clippy
        if: "!cancelled() && steps.dependencies.outcome == 'success'"
        run: cargo clippy --no-deps -- --deny=warnings
      - name: Clippy (no default features)
        if: "!cancelled() && steps.dependencies.outcome == 'success'"
        run: cargo clippy --no-deps --no-default-features -- --deny=warnings
      - name: Check formatting
        if: "!cancelled() && steps.checkout.outcome == 'success'"
        run: cargo fmt --check
